### ISSUE TITLE
Alphabetize arrays and objects

### ISSUE THREAD

**Issue by jessehattabaugh** [Alhadis/PPJSON#1]
I've been looking for something to automatically alphabetize the elements in JSON arrays. Would be cool if this were an option.

**Comment by Alhadis** [comment]
On it.

**Comment by Alhadis** [comment]
@jessehattabaugh : Do you mean to alphabetise both objects _and_ arrays? Because the latter would be effectively changing the data (making values appear to be indexed in an order that they're not).

The objects part makes perfect sense to me.

**Comment by Alhadis** [comment]
Hey, mate! =) Just pushed a [minor release to NPM](https://www.npmjs.com/package/ppjson). You can now alphabetise the output of objects by passing `-a` as a flag on command-line (or its lengthier counterpart, `--alphabetise`).

This works recursively, of course, meaning the enumerable properties of array contents will be sorted; however, the array indices themselves won't be modified.

(I'm really hoping I'm making sense, it's 6:23 am here in and I haven't slept in nearly 30 hours... haha ^^)

**Comment by jessehattabaugh** [comment]
Awesome! I was on vacation so I just saw this. You're right about the
arrays, though most of the time in JSON config files order doesn't make a
difference. This will help me keep my package.json dependency lists sorted.
Cheers!

**Comment by Alhadis** [comment]
Happy to help mate! :D Seriously.
